trigger:
  branches:
    include:
      - master  # or "master", depending on your branch

pool:
  vmImage: 'windows-latest'

variables:
  pythonVersion: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      cd projects/Calculate_age
      python calculate.py

    displayName: 'Run Python script'

  - script: |
     curl -L -o terrascan.zip https://github.com/tenable/terrascan/releases/download/v1.19.9/terrascan_1.19.9_Windows_x86_64.zip
     powershell -Command "Expand-Archive -Path terrascan.zip -DestinationPath terrascan -Force"
     
     
     cd terrascan
     terrascan.exe scan -t aws -i terraform -d %BUILD_SOURCESDIRECTORY%
    displayName: 'Run Terrascan'